# Generated by Django 4.0.2 on 2023-01-05 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
